language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r dev_requirements.txt
  - pip install --force-reinstall azure-nspkg==1.0.0
script:
  - pytest azure-kusto-data
  - pytest azure-kusto-ingest
deploy:
  provider: pypi
  user: microsoftkusto
  skip_upload_docs: true
  # password: use $PYPI_PASSWORD
  distributions: "travis_deploy" # Manual step
  on:
    tags: true
    python: '3.6'
    branch: master
