dist: xenial
sudo: required
language: python
os:
  - linux
env:
  - OPTIONAL=None
  - OPTIONAL=aio
  - OPTIONAL=pandas
python:
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  - if [[ -n "$TRAVIS_TAG" && "$TRAVIS_PYTHON_VERSION" == "3.7" ]]; then travis_terminate 0; fi; # Deploy on 3.7
install:
  - pip install -U pip
  - pip install -r dev_requirements.txt
  - if [[ $OPTIONAL != None ]]; then pip install -r dev_requirements_$OPTIONAL.txt;fi
  - pip install codecov coverage
  - if [[ $OPTIONAL == None ]]; then pip install ./azure-kusto-data ./azure-kusto-ingest; else pip install ./azure-kusto-data[$OPTIONAL] ./azure-kusto-ingest[$OPTIONAL];fi
  - pip freeze
before_script:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then black . --line-length 160 --check; fi
script:
  - pytest
after_success:
  - coverage report
  - codecov
deploy:
  provider: pypi
  user: microsoftkusto
  skip_upload_docs: true
  # password: use $PYPI_PASSWORD
  distributions: "travis_deploy" # Manual step
  on:
    tags: true
    python: '3.6'
    branch: master
