dist: trusty
sudo: required
cache: pip
language: python
matrix:
  include:
    - os: linux
      python: "2.7"
    - os: linux
      python: "3.4"
    - os: linux
      python: "3.5"
    - os: linux
      python: "3.6"
    - os: linux
      python: "pypy3.5-5.8.0"
    - os: osx
      osx_image: xcode7.3
      language: generic
  allow_failures:
    - os: osx
    - python: "3.3"
    - python: "pypy3.5-5.8.0"
    - python: "nightly"
  fast_finish: true
  - pip install --force-reinstall azure-nspkg==1.0.0
before_install:
  - if [[ -n "$TRAVIS_TAG" && "$TRAVIS_PYTHON_VERSION" != "3.6" ]]; then travis_terminate 0; fi; # Deploy on 3.6
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python3 -m venv venv; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi  
install:
  - pip install -U pip
  - pip install -r dev_requirements.txt
  - pip install codecov coverage
  - pip install ./azure-kusto-data ./azure-kusto-ingest
  - pip install --force-reinstall azure-nspkg==1.0.0
script:
  - pytest
after_success:
  - coverage report
  - codecov
deploy:
  provider: pypi
  user: microsoftkusto
  skip_upload_docs: true
  # password: use $PYPI_PASSWORD
  distributions: "travis_deploy" # Manual step
  on:
    tags: true
    python: '3.6'
    branch: master
