dist: trusty
sudo: required
cache: pip
language: python
matrix:
  include:
    - os: linux
      python: "2.7"
    - os: linux
      python: "3.5"
    - os: linux
      python: "3.6"    
  fast_finish: true
before_install:
  - if [[ -n "$TRAVIS_TAG" && "$TRAVIS_PYTHON_VERSION" != "3.6" ]]; then travis_terminate 0; fi; # Deploy on 3.6  
install:
  - pip install -U pip
  - pip install -r dev_requirements.txt
  - pip install codecov coverage
  - pip install ./azure-kusto-data ./azure-kusto-ingest
  - pip freeze
before_script:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then black . --line-length 120 --check; fi
script:
  - pytest
after_success:
  - coverage report
  - codecov
deploy:
  provider: pypi
  user: microsoftkusto
  skip_upload_docs: true
  # password: use $PYPI_PASSWORD
  distributions: "travis_deploy" # Manual step
  on:
    tags: true
    python: '3.6'
    branch: master
